- neva_name: PSOD_NEVA2                      # наименование системы для формирования имен файла

- database_config: !!python/tuple             # настройки доступа к базе данных  
  - localhost                                 # имя/адрес сервера, где запущена база данных 
  - root                                      # имя пользователя 
  - Spider@19128                              # пароль 
  - controlsystembase_dus                     # наименование базы данных
 
- data_dir: C:\PSOD_NEVA2_DATA                # папка расположения файлов данных

- unpak_dir: C:\PSOD_NEVA2_DATA\logs_reports  # папка расположения детальных отчетов и логов работы системы

- start_date_time: 2021-11-30 22:00:00        # дата время после которого надо отслеживать записи в базе данных зарегистрированных составов 

- start_freze_time: 10                        # время (сек), на которое задерживается выполнение основного алгоритма при первом запуске (для прогрузки базы данных итп)

- db_control_period: 60                       # период опроса базы данных на наличие новых записей о зарегистрированных составах (сек)




- slots_konfig_R: !!python/tuple # конфигурация модулей правой стороны системы

  - !!python/tuple  # общая конфигурация первого по ходу движения модуля для правой стороны 
    - 2D915140      # серийный номер модуля
    - 4             # число каналов данных в модуле (не изменять)
    - 1536          # число сэмплов за секунду в данных с канала (не изменять) 
    - 1             # режим обработки данных с модуля (0 -временные метки игнорировтаь, 1- временные метки применить) 

    - !!python/tuple # конфигурация масштабных коэффициентов первого по ходу движения модуля для правой стороны 
      - 15625.0     # Домножающий масштабный коэффициент для данных 0 канала данного модуля (для канала с ДПК = 1000)
      - 211860.0    # Домножающий масштабный коэффициент для данных 1 канала данного модуля (для канала с ДПК = 1000)
      - 178571      # Домножающий масштабный коэффициент для данных 2 канала данного модуля (для канала с ДПК = 1000)    
      - 1000        # Домножающий масштабный коэффициент для данных 3 канала даннного модуля (для канала с ДПК = 1000)  

  - !!python/tuple  # общая конфигурация второго по ходу движения модуля для правой стороны  
    - 2D881683      # серийный номер модуля
    - 4             # число каналов данных в модуле (не изменять)
    - 1536          # число сэмплов за секунду в данных с канала (не изменять) 
    - 1             # режим обработки данных с модуля (0 -временные метки игнорировтаь, 1- временные метки применить) 

    - !!python/tuple # конфигурация масштабных коэффициентов второго по ходу движения модуля для правой стороны 
      - 18939       # Домножающий масштабный коэффициент для данных 0 канала данного модуля (для канала с ДПК = 1000) 
      - 49397       # Домножающий масштабный коэффициент для данных 1 канала данного модуля (для канала с ДПК = 1000) 
      - 15578       # Домножающий масштабный коэффициент для данных 2 канала данного модуля (для канала с ДПК = 1000) 
      - 1000        # Домножающий масштабный коэффициент для данных 3 канала данного модуля (для канала с ДПК = 1000) 

- slots_konfig_L: !!python/tuple # конфигурация модулей левой стороны системы

  - !!python/tuple  # общая конфигурация первого по ходу движения модуля для левой стороны  
    - 2D915153      # серийный номер модуля
    - 4             # число каналов данных в модуле (не изменять)
    - 1536          # число сэмплов за секунду в данных с канала (не изменять) 
    - 1             # режим обработки данных с модуля (0 -временные метки игнорировтаь, 1- временные метки применить) 

    - !!python/tuple #конфигурация масштабных коэффициентов первого по ходу движения модуля для левой стороны
      - -50000       # Домножающий масштабный коэффициент для данных 0 канала данного модуля (для канала с ДПК = 1000)  
      - 139000       # Домножающий масштабный коэффициент для данных 1 канала данного модуля (для канала с ДПК = 1000) 
      - -85110       # Домножающий масштабный коэффициент для данных 2 канала данного модуля (для канала с ДПК = 1000)
      - 1000         # Домножающий масштабный коэффициент для данных 3 канала данного модуля (для канала с ДПК = 1000)

  - !!python/tuple  # общая конфигурация второго по ходу движения модуля для левой стороны 
    - 2D915066       # серийный номер модуля
    - 4              # число каналов данных в модуле (не изменять)
    - 1536           # число сэмплов за секунду в данных с канала (не изменять) 
    - 1              # режим обработки данных с модуля (0 -временные метки игнорировтаь, 1- временные метки применить) 
 
    - !!python/tuple #конфигурация масштабных коэффициентов второго по ходу движения модуля для левой стороны 
      - 91749        # Домножающий масштабный коэффициент для данных 0 канала (для канала с ДПК = 1000)  
      - -51913       # Домножающий масштабный коэффициент для данных 1 канала  (для канала с ДПК = 1000) 
      - 46922        # Домножающий масштабный коэффициент для данных 2 канала  (для канала с ДПК = 1000)
      - 1000         # Домножающий масштабный коэффициент для данных 3 канала  (для канала с ДПК = 1000) 

- dpk_config_R: !!python/tuple # конфигурация ДПК и расстояний между датчиками для правой стороны системы
  - 3                          # номер канала с первым ДПК в первом модуле (каналы модулей объединяются, общее число каналов для одной стороны = 8 (с 0 по 7),    
  - 7                          # номер канала со вторым ДПК во втором модуле (каналы 0-3 для первого модуля, каналы 4-7 для второго модуля)  
  - 45                         # пороговое значение сигнала (мВ) при наличии колеса на первом ДПК 
  - 45                         # пороговое значение сигнала при наличии колеса на втором ДПК  
  - 5.965                      # расстояние между первым и вторым ДПК 
  - 1.565                      # расстояние между первым ДПК и ТВС1 
  - 2.11                       # расстояние между первым ДПК и ТВС2 	
  - 2.66                       # расстояние между первым ДПК и ТВС3 
  - 3.165                      # расстояние между первым ДПК и ТВС4 
  - 3.705                      # расстояние между первым ДПК и ТВС5 
  - 4.28                       # расстояние между первым ДПК и ТВС6

- dpk_config_L: !!python/tuple # конфигурация ДПК и расстояний между датчиками для левой стороны системы
  - 3                          # номер канала с первым ДПК в первом модуле (каналы модулей объединяются, общее число каналов для одной стороны = 8 (с 0 по 7),   
  - 7                          # номер канала со вторым ДПК во втором модуле (каналы 0-3 для первого модуля, каналы 4-7 для второго модуля) 
  - 45                         # пороговое значение сигнала (мВ) при наличии колеса на первом ДПК 
  - 45                         # пороговое значение сигнала при наличии колеса на втором ДПК  
  - 5.965                      # расстояние между первым и вторым ДПК  
  - 1.615                      # расстояние между первым ДПК и ТВС1 
  - 2.125                      # расстояние между первым ДПК и ТВС2 
  - 2.66                       # расстояние между первым ДПК и ТВС3 
  - 3.225                      # расстояние между первым ДПК и ТВС4 
  - 3.744                      # расстояние между первым ДПК и ТВС5
  - 4.32                       # расстояние между первым ДПК и ТВС6 
 
- algoritm_config_LF: !!python/tuple # настройки для низкочастотной фильтрации сигнала - НЧ фильтром Баттерворта
  - 0.00015                          # нижний порог НЧ, Гц  
  - 15.0                             # верхний порог НЧ, Гц  
  - 3                                # порядок фильтра
  - 1536                             # число сэмплов за секунду в данных с канала (не изменять)

- algoritm_config_HF: !!python/tuple # настройки для низкочастотной фильтрации сигнала - ВЧ фильтром Баттерворта
  - 660                              # нижний порог ВЧ, Гц 
  - 760                              # верхний порог ВЧ, Гц      
  - 3                                # порядок фильтра
  - 1536                             # число сэмплов за секунду в данных с канала (не изменять)
 
- algoritm_config_LD: 0.3            # зона чувствительности ТВС вправо и влево от его оси, м  

- criteria_config_R: !!python/tuple  # настройки критериев для определения уровня дефектоности колеса у датчиков правой стороны

  - !!python/tuple
    - 60
    - 1
    - 11.75
    - 2
    - 40
    - 0.5
  - !!python/tuple
    - 65
    - 3
    - 11.75
    - 4
    - -40
    - 0.6
  - !!python/tuple
    - 70
    - 5
    - 11.75
    - 6
    - 150
    - 0.7

- criteria_config_L: !!python/tuple # настройки критериев для определения уровня дефектоности колеса у датчиков правой стороны

  - !!python/tuple
    - 60
    - 1
    - 11.75
    - 2
    - 40
    - 0.5
  - !!python/tuple
    - 65
    - 3
    - 11.75
    - 4
    - -40
    - 0.6
  - !!python/tuple
    - 70
    - 5
    - 11.75
    - 6
    - 150
    - 0.7

